### ISSUE TITLE
Excuse me, have you finished ？

### ISSUE THREAD

**Issue by myronliu347** [posva/vue-material-icons#1]

**Comment by posva** [comment]
No, I didn't. Have you created a vue plugin for Material design icons that supports morphing?

**Comment by myronliu347** [comment]
I now use the fonts icon,but I want to join the SVG icon in the components,so I'm looking forward to this project complete.

**Comment by posva** [comment]
The idea was to use https://github.com/alexk111/SVG-Morpheus to get morphing but svg icons have to be in a very specific format. I got something more or less working on https://github.com/posva/vue-mdl/tree/morpheus but I couldn't spend enough time on it so if you want to contribute, just tell me

**Comment by myronliu347** [comment]
o, thanks, I try.
